/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-09-26 07:30:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class board_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("	<title>게시판 글쓰기</title>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"../ckeditor/ckeditor.js\" ></script>\r\n");
      out.write("	<link rel=\"Stylesheet\" href=\"../style/default.css\" />\r\n");
      out.write("	<SCRIPT type=\"text/javascript\">\r\n");
      out.write("function check(){\r\n");
      out.write("    if(!bbs.subject.value){\r\n");
      out.write("        alert(\"제목을 입력하세요\");\r\n");
      out.write("        bbs.subject.focus();\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    if(!bbs.writer.value){\r\n");
      out.write("        \r\n");
      out.write("        alert(\"이름을 입력하세요\");\r\n");
      out.write("        bbs.writer.focus();\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("   /*  if(!bbs.content.value){            \r\n");
      out.write("        alert(\"글 내용을 입력하세요\");\r\n");
      out.write("        bbs.content.focus();\r\n");
      out.write("        return false;\r\n");
      out.write("    } */\r\n");
      out.write("    if(!bbs.pwd.value){            \r\n");
      out.write("        alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("        bbs.pwd.focus();\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    document.bbs.submit();\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 ");

        pageContext.include("/include/header.jsp");
     
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"pageContainer\">\r\n");
      out.write("        <div style=\"padding-top: 25px; text-align: center\">\r\n");
      out.write("            <!-- form 시작 ---------->\r\n");
      out.write("            <form name=\"bbs\" action=\"board_write.ok\" method=\"POST\">\r\n");
      out.write("                <table width=\"95%\" border=\"2\" align=\"center\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"20%\" align=\"center\">제목</td>\r\n");
      out.write("                        <td width=\"80%\" align=\"left\"><input type=\"text\"    name=\"subject\" size=\"40\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"20%\" align=\"center\">글쓴이</td>\r\n");
      out.write("                        <td width=\"80%\" align=\"left\"><input type=\"text\" name=\"writer\" size=\"40\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"20%\" align=\"center\">이메일</td>\r\n");
      out.write("                        <td width=\"80%\" align=\"left\"><input type=\"text\" name=\"email\" size=\"40\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"20%\" align=\"center\">홈페이지</td>\r\n");
      out.write("                        <td width=\"80%\" align=\"left\"><input type=\"text\" name=\"homepage\" size=\"40\" value=\"http://\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"20%\" align=\"center\">글내용</td>\r\n");
      out.write("                        <td width=\"80%\" align=\"left\"><textarea rows=\"10\" cols=\"60\" name=\"content\" class=\"ckeditor\"></textarea></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"20%\" align=\"center\">비밀번호</td>\r\n");
      out.write("                        <td width=\"80%\" align=\"left\"><input type=\"password\" name=\"pwd\" size=\"20\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"20%\" align=\"center\">첨부파일</td>\r\n");
      out.write("                        <td width=\"80%\" align=\"left\"><input type=\"file\" name=\"filename\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"2\" align=\"center\">\r\n");
      out.write("                            <input type=\"button\" value=\"글쓰기\" onclick=\"check();\" /> \r\n");
      out.write("                            <input type=\"reset\"  value=\"다시쓰기\" />\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("              </form>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
