/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-09-26 06:03:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import kr.or.bit.service.BoardService;

public final class board_005fwriteok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("kr.or.bit.service.BoardService");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	//request.getParameter("") ....
	//Board board = new Board();
	//board.setName = request.getParameter("") 
			
  //자동 전제 조건 : jsp?name=kglim&			

      out.write('\r');
      out.write('\n');
      kr.or.bit.dto.Board board = null;
      board = (kr.or.bit.dto.Board) _jspx_page_context.getAttribute("board", jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
      if (board == null){
        board = new kr.or.bit.dto.Board();
        _jspx_page_context.setAttribute("board", board, jakarta.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write('	');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("board"), request);
        out.write('\r');
        out.write('\n');
      }
      out.write('\r');
      out.write('\n');

	/*
	out.print(board.getSubject() + "<br>");
	out.print(board.getWriter() + "<br>");
	out.print(board.getEmail() + "<br>");
	out.print(board.getHomepage() + "<br>");
	out.print(board.getContent() + "<br>");
	out.print(board.getPwd() + "<br>");
	out.print(board.getFilename() + "<br>");
	*/	

	//out.print(board.getSubject() + "<br>");
	//out.print(board.getWriter() + "<br>");
    //단 jsp:useBean 성립  jsp:setProperty 자동화 ... 전제 ...
    //name="subject" 이름이  Board DTO 객체 memberfield명과  동일
    
    //DB 컬럼명 == DTO memberfield == input name 속성명과 같다 (자동화...)
    
    //write.jsp(클라이언트 화면) >> 처리 writeok.jsp >> DAO객체 생성, 처리 ... (x)
    //write.jsp(클라이언트 화면) >> 처리 writeok.jsp >> service 만 노출 >> 업무 ...
    
    BoardService service = BoardService.getInBoardService();
    int result = service.writeOk(board);
    
    //write.jsp 화면  >> writeok.jsp 처리 >> service >> dao > DB 작업 > 
    //return dao > return service >  writeok.jsp 결과처리 >> 이동 (공통) >> redirect.jsp
    		
    String msg="";
    String url="";
    if(result > 0){
    	msg ="insert success";
    	url ="board_list.jsp";
    }else{
    	msg="insert fail";
    	url="board_write.jsp";
    }
    
    request.setAttribute("board_msg",msg);
    request.setAttribute("board_url", url);

      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("redirect.jsp");
        return;
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
